# Session 5: arrays

In today's session, we'll learn about the *array* data type that *numpy* automatically provides for us. For us physicists and astronomers, this is arguably the single most important data type python provides. We'll use this in virtually every significant programming or data analysis task we carry out with *Python*. So it's well worth taking the time to really understand *arrays*.

## arrays

The data type *array* is defined in the *numpy* package.

That means every time we import *numpy*, the *array* data type is automatically made available to us.

Formally, *numpy* arrays go by the name of *ndarrays* (for N-dimensional arrays), but we will use the term *array* as a short-hand and always use it to refer to *numpy* *ndarrays*. 

Be aware of this though, because there is, in fact, an actual *array* data type defined in the "standard Python library" -- so if you google "Python arrays", you might not find the information you're expecting (about *numpy* *ndarrays*). 

In this course, we're never going to use the Python standard library array data type, so this isn't going to cause any confusion. 

Fundamentally, *arrays* are very similar to *lists*:

* *arrays* are *sequences*<br>

* *arrays* are *mutable*<br>

The main difference between *arrays* and *lists* is:

* all elements of an *array* must have the same data type

The restriction to a single data type makes *arrays* much more efficient to store than *lists*, since we don't have to store *type* information for each element.

It also makes *arrays* more suitable for numerical calculations in which we often want to work on vectors and matrices that contain numbers (most commonly *floats*.)

### vectors (1D arrays)

The single most common and useful data structure for data analysis is a 1-dimensional *array*, i.e. a *vector*.

*numpy* provides several ways of creating vectors:

In [25]:
import numpy as np

#convert a list to an array
a1 = np.array([0.0, 1.0, 2.0, 4.0, 5.0]) 

#use "arange" (array equivalent to "range" for lists)
#if argument is given as float, output is float also
a2 = np.arange(5.0)

#creating an array filled with a given number of (float) zeros
a3 = np.zeros(5)

#creating an array filled with a given number of (float) ones
a4 = np.ones(5)

print a1
print a2
print a3
print a4

[ 0.  1.  2.  4.  5.]
[ 0.  1.  2.  3.  4.]
[ 0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.]


Since *arrays* are *mutable*, we can change individual elements once we've created an *array*

In [26]:
a2 = np.arange(5.0)
print a2
a2[0] = 10.0
print a2

[ 0.  1.  2.  3.  4.]
[ 10.   1.   2.   3.   4.]


As we've seen before, if you accidentally or intentionally try to do something that shouldn't be possible, *Python* tries to guess what you meant.

This is both good and bad. On the one hand, it's convenient for quick-and-dirty interactive analysis -- more often than not, we can get away with sloppy style and still get the results we want.

On the other hand, *Python's* tendency to guess means that a simple typo in a program -- e.g. typing "5" instead of "5.0" -- won't necessarily cause a formal error (the program will run), but the program might produce plausible looking, but incorrect output.

Here is an example of *Python* trying to guess what you meant:

In [27]:
a = np.arange(5) 
print a
a[0] = 3.9
print a

[0 1 2 3 4]
[3 1 2 3 4]


Note how *Python* did not fall over with an error when we tried to assign a *float* to an *array* or *ints*!

Instead, it implicitly and silently converted the *float* to an *int* -- and it didn't even round, but instead just truncated the *float*! This is probably not what we wanted. 

In fact, the most likely situation in which we might find the sort code snippet above that we **meant** to write:

In [28]:
a = np.arange(5.0)
print a
a[0] = 3.9
print a

[ 0.  1.  2.  3.  4.]
[ 3.9  1.   2.   3.   4. ]


All the built in stuff that's available for sequences (and particularly *lists*) is available for *arrays* also. For example:

In [29]:
a1 = np.arange(5.,0.,-1.)
print 'the length function gives: ', len(a1)
print 'the array is', a1
a2 = a1[:3] #slicing
print 'the sliced array is', a2

the length function gives:  5
the array is [ 5.  4.  3.  2.  1.]
the sliced array is [ 5.  4.  3.]


Also, most of the *methods* we've already seen for *lists* are available for *arrays*, too, as well as some new ones. For example:

In [30]:
a1 = np.arange(5.,0.,-1.)
print 'the original array is', a1
a1.sort()
print 'the sorted array is', a1

the original array is [ 5.  4.  3.  2.  1.]
the sorted array is [ 1.  2.  3.  4.  5.]


There is little point covering all of the available *methods* here, but do familiarize yourself with them by taking a look here: 

http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html

In addition, we now have acccess to a whole bunch of *numpy* functions that can act efficiently on entire arrays at once. For example:

In [31]:
a1 = np.arange(3.0)
print a1
a1 = np.sin(a1)
print a1

[ 0.  1.  2.]
[ 0.          0.84147098  0.90929743]


##### Exercise

Write a function that, given some array x and an integer parameter n, returns as output the polynomial f(x) = n*x^n. 

##### Exercise

Write a program that creates 100 x-values space regularly between 0 and 20 and calls your function with this set of x-values for n = 0, 1, 2, 3, 4, 5. The program should then provide summary statistics (at least the mean and standard deviation) on the y-values in each case. It should also numerically integrate the functions. For the integration, you can rely on whatever functions you find in *numpy* or *scipy*.

### matrices (2D arrays)

*Python* also makes it easy to create and use 2-dimensional arrays. These provide a natural way to store matrices or images, for example.

We can create a matrix via the *zeros* and *ones* functions we already saw above:

In [32]:
#create a 3(rows) x 4(columns) matrix and fill with zeroes
x0 = np.zeros((3, 4))

#create a 3(rows) x 4(columns) matrix and fill with ones
x1 = np.ones((3, 4))

print 'x0:'
print x0
print
print 'x1:'
print x1

x0:
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

x1:
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


We can also convert a *list* of *lists* (or a *list* of *tuples*) to an array:

In [33]:
#create a list of lists and convert to a 2-D array
l2d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 10, 12]]
xl = np.array(l2d)

#create a list of tuples and convert to a 2-D array
lt2d = [(1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 10, 12)]
xlt = np.array(l2d)

print 'xl:'
print xl
print
print 'xlt:'
print xlt

xl:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]

xlt:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]


We might wonder a bit about the second conversion, from a *list* of *tuples*: after all, *tuples* are supposed to be *immutable*, but *arrays* are *mutable*.

Let's check that this actually remains the case here. First, let's try to modify an element in our array:

In [34]:
xlt[1][2] = 20
print xlt

[[ 1  2  3  4]
 [ 5  6 20  8]
 [ 9 10 10 12]]


Now, let's try to modify an element in the *list* of *tuples*:

In [35]:
lt2d[1][2] = 20
print lt2d

TypeError: 'tuple' object does not support item assignment

OK, so things do work as expected: we can modify elements of the array that was constructed from the *list* of *tuples*, but we can't modify elements in the *list* of *tuples* itself. 

So what happens is basically just that *Python* copies the values of the *tuples* into *array* elements, and these elements are thereafter modifiable. 

This is actually not all that surprising -- after all, we can also convert tuples into lists:

In [36]:
t = (1, 2, 3)
l = list(t)
print t, type(t)
print l, type(l)

(1, 2, 3) <type 'tuple'>
[1, 2, 3] <type 'list'>


Let's get back to the 2-D arrays.

*Python* actually does a rather nice job of printing matrices for us:

In [37]:
#create a list of lists and convert to a 2-D array
l2d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 10, 12]]
xl = np.array(l2d)
print xl

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]


Note how *Python* printed this as an actual matrix, i.e. as a 2-D object with rows and columns.

Similarly, when we call *zeros* or *ones*, we specify the dimensions of the array as<br>
"(rows, columns)":

In [38]:
a = np.zeros((2,4))
print a

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


The dimensionality -- or *shape* -- of any array can be queried via the *shape* "attribute":

In [39]:
a.shape

(2, 4)

This shape is a *tuple*, and the notation for 2-D arrays is generally "first rows, then columns".

So the shape here tells us that the object "a" contains 2 rows and 4 columnns, consistent with the way *Python* printed the array.

But what the hell is an "attribute"?

##### attributes

As we can tell from the notation, *attributes* are similar to *methods*: they are things that are automatically defined for a given data type. 

But while *Methods* are *functions* that are defined for each object belong to a given data type, *attributes* are specific pieces of information about the object in question. Thus, unlike *methods*, *attributes* don't **do** anything.

The *shape* of an array is one such *attribute* for *ndarrays*; another would be the total *size* (i.e. the number of elements it contains):

In [40]:
a.size

8

The syntax for *attributes* is exactly the same as for *methods*, except that we don't need the parentheses "()". If you want to know what *attributes* are available for *arrays* (or other data types), check the relevant *Python* documention, for example

http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html

Again, my advice here is not to try to memorize all of the available *function and *methods* and *attributes* -- just familiarize yourself a bit with them, to get a feel for what's available. Then, when you actually try to solve a programming task, know where to check whether and how a suitable thing is available and how to use it. 

Eventually, the things you find you use a lot will become second nature, and you won't have to look them up any more. And the things you don't use all that much -- well, looking those up when you do need them seems like a sensible strategy...

##### row vectors and column vectors

If (or when) you've covered matrices in your mathematics course, you'll know that, mathematically, there is (sort of) a difference between a row vector and a column vector. For example, when we represent a dot product as a matrix multiplication, we write one of the vectors as a row vector, and the other as a column vector.

This is not a mathematics, course, however, so we're not going to delve into a lot of detail here. However, since part of the point of this section on 2-D *arrays* is to highlight that *Python* can be used as a nice way of doing numerical work with matrices, it's worth just also pointing out that this extends even to the distinction between row and column vectors. 

Specifically, *Python* allows us to have arrays that are formally 2-dimensional, but for which one or the other dimension is 1. This then opens up the possibility of distinguishing between row and column vectors.

For example, suppose we have created the simple 1-D vector x1d:

In [41]:
x1d = [1, 2, 3]
print x1d

[1, 2, 3]


We can now create a formally 2-dimensional version of this which contains 1 row and 3 columns by using the *numpy* *reshape* function:

In [42]:
x2d_row = np.reshape(x1d, (1, 3))
print x2d_row

[[1 2 3]]


Note how this has **two** square brackets, signalling that this is a 2-D array (it's just that one of the dimensions is empty).

Now, here it comes: we can also make a **column vector** from x1d, just by switching the dimensions in *reshape*:

In [43]:
x2d_col = np.reshape(x1d, (3, 1))
print x2d_col

[[1]
 [2]
 [3]]


Note how this is even nicely printed as a column vector for us!

You all probably hate me by now -- all of this stuff can get awfully confusing! Here is the thing: in this course, we're probably not going to do all that much work with 2-D and higher-dimensional *arrays*. And, in fact, for most of our data analysis tasks -- which is what we'll be using *Python* for later in the course -- 1-D *arrays* are all that we need most of the time. 

Nevertheless, it's really useful to be at least aware of *Python's* capabilities in this respect. There may come a time when you solve a numerical linear algebra problem using matrices, for example. Knowing *Python* and knowing that *Python* has a ton of built-in support for this sort of work will hopefully make it much less scary to tackle such a problem in future.

Let's see just one quick example of how convenient *Python* makes computations with matrices.

The following example is stolen directly from Hans Fangohr's excellent *Python* textbook.

In [44]:
import numpy as np
from numpy import random
A = np.random.rand(5, 5)    # generates a random 5 by 5 matrix
x = np.random.rand(5)       # generates a 5 - element vector
b = np.dot(A, x)            # multiply matrix A with vector x

print 'A:'
print A
print
print 'x:'
print x
print
print 'b:'
print b                     # the result of the matrix multiplication

from numpy import linalg as LA
x2 = LA.solve(A, b)         # solve the matrix equation Ax = b for x

print
print 'x2:'
print x2

A:
[[ 0.99227312  0.77847828  0.75847686  0.50186218  0.18701308]
 [ 0.89209548  0.94526067  0.4210317   0.21152592  0.48981118]
 [ 0.86466101  0.40316567  0.29596753  0.47454821  0.848287  ]
 [ 0.35991876  0.72582496  0.34127081  0.29892495  0.13684236]
 [ 0.18899314  0.43368449  0.20926117  0.93747874  0.46223143]]

x:
[ 0.48692048  0.57502107  0.84006376  0.20412152  0.08673825]

b:
[ 1.68663051  1.4172802   1.07192595  0.95219218  0.74864781]

x2:
[ 0.48692048  0.57502107  0.84006376  0.20412152  0.08673825]


We will not introduce any more matrix computations for now. Just be aware that *numpy* provides a host of powerful and convenient tools for you, should you need them.

#### 2-D arrays as lists of lists:
#### extracting elements and sub-matrices

Something we will often want to do is extract specific parts of a matrix. 

The most obvious is that we might want to extract a particular element:

In [45]:
l2d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 10, 12]]
xl = np.array(l2d)
print xl

top_left = xl[0][0]
print 'top_left = ', top_left
bottom_right = xl[2][3]
print 'bottom_right = ', bottom_right
zero_two = xl[0][2]
print 'element in row 0, col 2 =', zero_two
one_three = xl[1][3]
print 'element in row 1, col 3 =', one_three

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]
top_left =  1
bottom_right =  12
element in row 0, col 2 = 3
element in row 1, col 3 = 8


We might also want to extract a particular sub-matrix, say the 2x2 matrix in the top left.

Here is a first attempt at this:

In [46]:
two_by_two = xl[0:2][0:2]
print two_by_two
print
print 'This is not our 2x2 matrix!'

[[1 2 3 4]
 [5 6 7 8]]

This is not our 2x2 matrix!


**What happened?**

In order to understand this behaviour, we just have to know and remember a few key points:

* 2-D *arrays* are fundamentally *lists* of *lists*

* each element in the outer list stores (corresponds to) a single row

* there is no equivalent element in the array that holds a single column

* expressions line "print array[0:2][0:2]" are evaluated sequentually<br><br>
    * array[0:2] refers to the first two rows of "array"
        * this is still a 2-D *array*!<br><br>
    * array[0:2][0:2] refers to the first two rows of "array[0:2]"
        * this is the **same** two rows!

Let's take another look at our "problem":

In [47]:
print xl
print
two_by_two = xl[0:2][0:2]
print two_by_two

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]

[[1 2 3 4]
 [5 6 7 8]]


This should make sense now!

"xl[0:2]" says *"return the first two rows of the array xl"*
* The output of this is itself an array (with two rows)! <br><br>

"xl[0:2][0:2]" says *"take the first two rows of the array given by xl[0:2]"*
* So we just get both of the rows of xl[0:2] again!<br><br>

Note that the notation for accessing actual *lists* within *lists* works in exactly the same way.

If this still doesn't make sense, we can make it even more explicit. Writing xl[0:2][0:2] is literally just a short-hand for the following sequence of operations:

In [48]:
print xl
#
OUT = xl[0:2]
print
print OUT
#
OUT2 = OUT[0:2]
print
print OUT2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]


So how **do** we extract a sub-matrix?

Well, the obvious way is to write a loop that cycles through the elements we want. How do we do that?

In our example (grabbing to 2x2 sub-matrix on the top-left), we want to access elements (0, 0) (0, 1) (1, 0) and (1, 1) of the full matrix. So we need to cycle through something like rows = 0,1 and cols = 0,1.

Let's first of all just grab the relevant elements by looping over the array:

In [49]:
print 'The full matrix:'
print xl
print
rows = np.arange(2)
cols = np.arange(2)
print 'rows = ',rows, 'and cols = ',cols
print
for row in rows:
    for col in cols:
        print xl[row][col]


The full matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]

rows =  [0 1] and cols =  [0 1]

1
2
5
6


So this gives us the correct elements, but we also want to stuff them into an actual 2-D array.

This is easy: we just need to first create that array (with the right *shape*) and then stuff the relevant elements into it.

Let's put this together and create the sub-matrix we want:

In [50]:
submatrix = np.zeros((2,2))
rows = np.arange(2)
cols = np.arange(2)
print 'rows = ',rows, 'and cols = ',cols
print
for row in rows:
    for col in cols:
        submatrix[row][col] = xl[row][col]
print 'The submatrix is:'
print submatrix

rows =  [0 1] and cols =  [0 1]

The submatrix is:
[[ 1.  2.]
 [ 5.  6.]]


##### Exercise

Modify the code above to extract the 3x3 matrix at the top left.<br>
Modify it again to extract the 3x3 matrix at the bottom right.<br>
Modify it yet again to extract the sub-matrix defined by row 1:2 and columns 1:2.

##### Exercise

Write and save a function that takes as input an arbitrary 2-D array and a tuple defining the top-left and bottom-right corners of the sub-matrix of the array that the function should extract. The function should then extract that sub-matrix, store it in a 2-D array and return this sub-matrix. The function should also check for obvious input errors: it should return gracefully with an error message if the sub-matrix actually extends beyond the edges of the input array, or if the dimensions of the array (or the tuple defining the sub-matrix) are not consistent with what the function is assuming.

#### Optional topic: advanced indexing and numpy.ix_

*numpy* actually provides a neat (and faster) way of doing this sort of thing without explicit looping, via a little bit of magic called "advanced indexing". 

We're not going to go into this in any detail at all here -- as the name implies, this is really a more advanced topic and not something we absolutely need to write useful *Python* programs. Instead, we'll just look at a couple of examples to see how it works. Those of you who are interested and feel adventurous may then want to look into it some more (e.g. here: http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html )

So, basically, when we access an array with the "array[x][y]" notation, the things in the "[ ]" tell *Python* which elements to access -- either directly (i.e. x and y can be *ints*) or via slicing (i.e. they can be ranges denoted by things like "1:2"). However, it turns out the thing inside the "[ ]" can also be something like a *list* or an *array* (or a tuple containing those things). In that case, *Python* interprets things a bit differently. 

The easiest way to understand this is by example. Suppose we want to access the element in colunmn 1 in row 0, column 0 in row 1 and column 3 in row 2. The advanced indexing way to do this is as follows:

In [51]:
print xl
rows = np.array([0, 1, 2])
cols = np.array([1, 0, 3])
print
print xl[rows,cols]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]

[ 2  5 12]


One particularly clever thing about advanced indexing is that, if you give one row and one column vector in an array "[ ]", it assumes you're not just talking about individual elements anymore, but about sub-matrixes.

For example:

In [53]:
rows = np.array([0, 1])
cols = np.array([0, 1])
rows = np.reshape(rows, (2, 1))
cols = np.reshape(cols, (1, 2))
print rows
print
print cols
print
print xl[rows, cols]

[[0]
 [1]]

[[0 1]]

[[1 2]
 [5 6]]


Note that we have to make a column vector that specifies the rows, and a row vector that specifies the columns.

That makes sense though: we can think of row vector "cols" = [[0 1]]" as the horizontal "header" of the table defined by the matrix, and the column vector rows as the vertical row labels for the table.

As a convenient shorthand, python does allow us to us slicing notation as well. So, for example, "a[1:3, 2:4]" will be interpreted by python as "a[[1,2],[2,3]]", which is a very convenient way to make sub-matrices:

In [64]:
print xl
two_by_two = xl[0:2, 0:2]
print
print two_by_two

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]

[[1 2]
 [5 6]]


We can also use this same notation to conveniently extract column vectors from a matrix (but note that they'll be "re-shaped" - see below -- into row vectors then):

In [66]:
col2 = xl[:,1]
print col2

[ 2  6 10]


Finally, *numpy* even provides us with a built-in function called "ix_" that creates the row and column vectors we need to extract specific rows and columns from a matrix.

It's easiest to illustrate this by example again:

In [54]:
print 'The original matrix:'
print xl
print
print 'Output from ix_'
print np.ix_([0,1],[0,1])
print
print 'The sub-matrix'
print xl[np.ix_([0,1],[0,1])]

The original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]

Output from ix_
(array([[0],
       [1]]), array([[0, 1]]))

The sub-matrix
[[1 2]
 [5 6]]


If we instead wanted, say, the sub-matrix defined by rows 0 and 1 and columns 1 and 2, we can simply write:

In [55]:
print 'The original matrix:'
print xl
print
print 'Output from ix_'
print np.ix_([0,1],[1,2])
print
print 'The sub-matrix'
print xl[np.ix_([0,1],[1,2])]

The original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]

Output from ix_
(array([[0],
       [1]]), array([[1, 2]]))

The sub-matrix
[[2 3]
 [6 7]]


### Higher-dimensional arrays

*Python* naturally provides support for higher dimensional *arrays*. These work pretty much exactly as we'd expect, based on how 1-D and 2-D *arrays* work.

In this course, we're not going to deal with higher dimensional *arrays* any further, but just be aware that they exist.

##### Exercise

Suppose you've done an experiment in which we've measured the temperature in a regular grid of x, y, z positions in a square box. Write a function that takes as input the number of points in your data set along each axis (as a *tuple*) and creates a 3-D array that can store the temperatures you've measured.<br>

Write another function that can access the temperature at a given grid point (identificed by its 3-D index i, j, k in the x, y, z directions).<br>

Test your functions by setting up some small pieces of mock data by hand and calling your functions.

##### Exercise

Now suppose the temperature was not measured along a regular grid, but at a bunch of fairly random x, y, z locations in the box. You still need to store the temperatures, but now you also need to store the actual positions alongside the temperatures. Modify your function so that it creates an array that can simultaneously store all of the relevant information. What data type should you use for each array element?

### Converting and reshaping arrays

*Python* makes it fairly easy to convert between *arrays*, *lists* and *tuples*. 

For 1-D *arrays*, it's really trivial:

In [56]:
array1d = np.array([1, 2, 3, 4])
print array1d
#
list1d = list(array1d)
print list1d

[1 2 3 4]
[1, 2, 3, 4]


For 2-D arrays, we just have to be a bit careful to be clear what we are telling *Python*. For example:

In [57]:
array2d = xl
print array2d
#
list2d = list(array2d)
print list2d

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 10, 12])]


This did **not** produce a *list* of *lists*, but a *list* of *arrays*, which makes sense when we think about it.

How would we convert to a *list* of *lists*?

Conveniently, *numpy* has a built-in *function* for this, within the *module* *ndarray*:

In [58]:
list2d = np.ndarray.tolist(array2d)
print list2d

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 10, 12]]


There is also a function for the inverse operation, converting from a *list* (or *list* of *lists*) to an *array*:

In [59]:
new_array2d = numpy.asarray(list2d)
print new_array2d

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]


##### Exercise

Write and test a function that will swap two user-defined rows of a given 2-D array.

##### Exercise: Tic-Tac-Toe or Connect 4

We have been thinking using a hypothetical program that will play tic-tac-toe throughout this coudrse. We have been doing this as a way to help us think concretely about how the things we are learning actually help us solve a particular problem. Let's turn the hypothetical program into a real one!

Write a program that will have the computer play either Tic-Tac-Toe or Connect 4 against the user. (Remember that such a Connect 4 program is actually your first assessed assignment!)

I suggest the following strategy:

* the game board can be represented conveniently as an array
* at each step, the user specifies the location where they want to put their "X" or "O" (or Connect 4 symbols)
    * this is the one thing we have not covered yet: interactive input
    * all you need to know for this will be provided below
    * the way this works is different between tic-tac-toe and Connect 4
        * in tic-tac-toe, you place symbols directly into the position you want
        * in Connect 4, you just choose a column to drop your symbol into
* within the program, you might want to use *ints* to represent "X" and "O" (or the c
    * this might make it easier for you to check if somebody has won...
* the computer's moves should be random
    * you can use *numpy*'s random number generation functions to create those moves
* for both the computer and the user, you'll need to check that the move they are trying is legal
    * if the user is trying to make a legal move:
        * give an informative error:
            * "position out of bounds"
            * "position already occupied"
        *  and prompt for new input 
    * if the computer makes an illegal move
        * keep generating random moves until we get a legal one
* after each move by a player, print the matrix representing the current state of the game
* the game finishes when either
    * one player has three "X"s or "O"s in a line (tic-tac-toe) or 4 symbols in a line (Connect 4)
        * that player wins!
    * the entire game board (array) is filled
        * it's a draw!

Here is the one thing you need to know that we haven't learned yet: how do we accept user input? 

The easiest way to do this is via the "input" function. This is pretty clever, in that it tries to guess what sort of data type is being read by looking at the data itself.

In [60]:
i = input('enter an integer: ')
print i, type(i)

enter an integer: 1
1 <type 'int'>


In [61]:
f = input('enter a float: ')
print f, type(f)

enter a float: 1.0
1.0 <type 'float'>


Let's say we want the user to enter "1,2" (for position row = 1, col = 2). We then have to convert the string "1,2" into a tuple of ints.

In [62]:
i, j = input('enter two integers: ')
print i, type(i)
print j, type(j)

enter two integers: 1


TypeError: 'int' object is not iterable

Tic-tac-toe or Connect 4 are really nice exercises, because they involves just about every concept we've come across so far. You'll need to use loops, if-then statements and numpy functions, define your own functions and create, access and use arrays. I should also get you to look some more at all the various functions that are now available for your pleasure, be it directly built in to python (e.g. *input*) or built into *numpy* or *scipy* (e.g. the random numbers you'll want to generate).

Oh, and you get to play tic-tac-toe and/or Connect 4 against the computer at the end!

Ready, Player One?

(That's a pretty good book, by the way....)